### ISSUE TITLE
New OpenJ9 website design

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#182]
This epic contains issues for the redesign and development of a new OpenJ9 website.

New site will have:

- Home page
- About page
- Performance page
- News page

Other possible pages:

- User stories

Source for the new website will be stored in the `vnext` branch. The built content of this branch will be hosted on gh-pages for previewing (requires Jenkins build/deploy).

When all the web dev and content work is complete:

- [ ] all artifacts should be checked for a license & appropriate copyright.
- [ ] the pipeline scripts should be added to the branch 
- [ ] xdump and xtrace option builders need to go back in
- [ ] performance `.md` files need to go back in or be adapted to the new website 
- [ ] diff to ensure nothing else is missing

**Comment by pshipton** [comment]
Looks good!
Once concern is that once the website goes live, we'll loose the following
https://www.eclipse.org/openj9/oj9_resources.html
https://www.eclipse.org/openj9/oj9_faq.html

**Comment by SueChaplain** [comment]
>Once concern is that once the website goes live, we'll loose the following
>https://www.eclipse.org/openj9/oj9_resources.html
>https://www.eclipse.org/openj9/oj9_faq.html

These pages have never been included in the re-design and I thought that was made clear during earlier design reviews.

The resources page has always been problematic to keep up to date, which does not present a good image to our users. There are some good articles on there, but some are quite dated. Please indicate which ones are valuable and we can create a page in the user documentation.

The FAQ answered many questions that our users had when the project formed in September 2017.  We now have a wikipaedia page, which many would use as a learning resource instead. Some of the questions can also be answered by reading the About page. Please indicate which FAQs you believe are still relevant but missing.

**Comment by pshipton** [comment]
> These pages have never been included in the re-design and I thought that was made clear during earlier design reviews.

Yes it was, I just don't want to loose useful resource. Not asking to keep this as part of the website. I like the idea of putting links to relevant articles in the user doc. Another option is an OpenJ9 blog with a listing. I'm good to drop the FAQs given the wikipedia page.

We should ask the authors of the articles which ones they want to keep referencing, but I've started a list below.
@mstoodle @DanHeidinga @vijaysun-omr @mpirvu @tajila @amicic @babsingh @dsouzai 

https://mstoodle.github.io/EclipseOpenJ9JitVerboseLogs/
https://www.slideshare.net/TobiAjila1/how-to-build-a-debuggle-runtime
https://developer.ibm.com/javasdk/2017/09/18/reducing-garbage-collection-pause-times-concurrent-scavenge-guarded-storage-facility/
https://developer.ibm.com/javasdk/2017/09/25/concurrent-scavenge-using-guarded-storage-facility-works/
https://developer.ibm.com/javasdk/2017/09/25/still-paying-unused-memory-java-app-idle/
https://www.slideshare.net/MarkStoodley/under-the-hood-of-the-testarossa-jit-compiler
https://www.ibm.com/developerworks/library/j-class-sharing-openj9/

**Comment by ashu-mehra** [comment]
Can these articles be moved to Eclipse OpenJ9 blog?

**Comment by pshipton** [comment]
> Can these articles be moved to Eclipse OpenJ9 blog?

I suppose if the author(s) own the entire content of the article, and agree, and make any adjustments necessary to make it appropriate for OpenJ9, then the author(s) can create an OpenJ9 blog for review and publish.

**Comment by mstoodle** [comment]
I would be ok with moving the verbose logs blog to the openj9 blog. The "under the hood" link is a presentation I gave at Java One in 2016, so it should probably stay as a slideshare link, but I guess I could write a blog article around those rough topics (everything old is new again!).

I'm also happy with the redesign. Big thanks for catching the resource links that won't cross over, Peter!

**Comment by pshipton** [comment]
Another place we could easily add the existing links is in https://github.com/eclipse/openj9/blob/master/README.md. There are already some links at the bottom. There is currently a link to the website resources page, but that is being removed via https://github.com/eclipse/openj9/pull/9687

**Comment by DanHeidinga** [comment]
The redesign gets a +1 from me as well.

I ported the links Peter identified above to the README.  We can move others (or not) in additional PRs if there's anything else that should be moved.

See https://github.com/eclipse/openj9/pull/9691

**Comment by pshipton** [comment]
+1

**Comment by pshipton** [comment]
Everything that seemed relevant in the [Resources](https://www.eclipse.org/openj9/oj9_resources.html) and [FAQ](https://www.eclipse.org/openj9/oj9_faq.html) is added to https://github.com/eclipse/openj9/blob/master/README.md.

If somebody wants another link from Resources added to the README, pls open a PR to add it.

**Comment by SueChaplain** [comment]
Website ready for publishing. Closing this epic
